.\" Source: ./cons.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH cons 3 "Aug 30, 2018" plm-exercises "plm-exercises Reference"

.SH NAME
\fBcons\fR \-\- Console Input and Output

.SH DESCRIPTION
Module for Console Input and Output\.

.SH USES
dos\.def
