.\" Source: ./fio.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH fclose 3 "Aug 25, 2018" fio "fio Reference"

.SH NAME
\fBfclose\fR \-\- close a file

.SH DESCRIPTION
Closes a file\.

.SH PARAMETERS
pfile \- pointer to file data

.SH RETURN VALUE
Doesn't return anything\.
