.\" Source: ./fio.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Mar  7 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH fio 3 "Oct 22, 2018" plm-exercises "plm-exercises Reference"

.SH NAME
\fBfio\fR \-\- File Input and Output

.SH DESCRIPTION
Module for reading and writing to files\.

.SH USES
dos\.def, cons.asm
