.\" Source: ./fio.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH freadchr 3 "Aug 30, 2018" fio "fio Reference"

.SH NAME
\fBfreadchr\fR \-\- read a character from a file

.SH DESCRIPTION
Reads a character from a file that has been opened previously in
read\-only or read/write mode\.

.SH PARAMETERS
pfile \- pointer to file data
pchar \- pointer to the character to set

.SH RETURN VALUE
0 on success
\-1 on error
