.\" Source: ./fio.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Mar  7 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH ftrunc 3 "Oct 22, 2018" fio "fio Reference"

.SH NAME
\fBftrunc\fR \-\- truncate the file

.SH DESCRIPTION
Truncates the file at the current position\.  The file should be in
opened writable mode\.

.SH PARAMETERS
pfile \- pointer to file data

.SH RETURN VALUE
Returns 0 on success and \-1 on error\.
