.\" Source: ./cons.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH prchr 3 "Aug 25, 2018" cons "cons Reference"

.SH NAME
\fBprchr\fR \-\- print single ASCII character

.SH DESCRIPTION
Prints a single character givan as argument of type byte\.

.SH PARAMETERS
chr \- character to print

.SH RETURN VALUE
Doesn't return anything\.
