.\" Source: ./cons.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH prhexbyte 3 "Aug 20, 2018" cons "cons Reference"

.SH NAME
\fBprhexbyte\fR \-\- print a byte in hexadecimal form

.SH DESCRIPTION
Prints a byte in hexadecimal lowercase form\.

.SH PARAMETERS
b \- byte to print

.SH RETURN VALUE
Doesn't return anything\.
