.\" Source: ./cons.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH prhexword 3 "Aug 24, 2018" cons "cons Reference"

.SH NAME
\fBprhexword\fR \-\- print a word (16\-bits) in hexadecimal form

.SH DESCRIPTION
Prints a word in hexadecimal lowercase form, without spaces, using 4
characters, zeros are added if needed so that the total of printed
characters be always four\.

.SH PARAMETERS
w \- word to print

.SH RETURN VALUE
Doesn't return anything\.
