.\" Source: ./cons.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Mar  7 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH println 3 "Oct 22, 2018" cons "cons Reference"

.SH NAME
\fBprintln\fR \-\- Prints a string followed by a CRLF

.SH DESCRIPTION
Prints a string and then CRLF afterwards\.

.SH PARAMETERS
pstr \- pointer to the null\-terminated string to print

.SH RETURN VALUE
Doesn't return anything\.
