.\" Source: ./cons.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH prstr 3 "Aug 24, 2018" cons "cons Reference"

.SH NAME
\fBprstr\fR \-\- Prints a null\-terminated 7\-bit ASCII string\.

.SH DESCRIPTION
Print the string on the console\.

.SH PARAMETERS
pstr \- address of the first character of the string

.SH RETURN VALUE
Doesn't return anything\.
