.\" Source: ./cons.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH readkey 3 "Aug 24, 2018" cons "cons Reference"

.SH NAME
\fBreadkey\fR \-\- Read a single keypress (modifiers not included)
DESCRPTION
Reads a single key and stores it at the address pointed by the pkey
parameter\.

.SH PARAMETERS
pkey \- address of the word value which has to be filled with data from
the key press

.SH RETURN VALUE
Doesn't return a value\.
