.\" Source: ./str.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Mar  7 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH strcmp 3 "Oct 22, 2018" plm-exercises "plm-exercises Reference"

.SH NAME
\fBstrcmp\fR \-\- compare two strings

.SH DESCRIPTION
Compares two strings and returns 0 if they are equal, \-1 or 1 if the
first string is before or after in code\-point order\.

.SH PARAMETERS
pstr1 \- first string
pstr2 = second string

.SH RETURN VALUE
Returns an integer telling if the first string is before, equal or
after in code\-point ordering the second string\.
