.\" Source: ./sys.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Aug 19 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH sys 3 "Aug 20, 2018" plm-exercises "plm-exercises Reference"

.SH NAME
\fBsys\fR \-\- System library

.SH DESCRIPTION
Module that contains system\-related functions\.

.SH USES
dos\.def
