.\" Source: ./str.asm
.\" Generated with ROBODoc Version 4\.99\.43 (Mar  7 2018)
.\" ROBODoc (c) 1994\-2015 by Frans Slothouber and many others\.
.TH xstr2byte 3 "Oct 22, 2018" str "str Reference"

.SH NAME
\fBxstr2byte\fR \-\- convert a string to number and return a byte

.SH DESCRIPTION
Converts a hexadecimal representation of a number to a number and
returns it as a single byte\.

.SH PARAMETERS
pstr \-\- pointer to the string to read

.SH RETURN VALUE
Returns the value represented by the string\.
